### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by kudlav** [Moustachauve/WLED-Native-Android#6]
Hi, it would be great if you could publish this app in F-Droid store.

**Comment by Moustachauve** [comment]
I don't plan on publishing my app to F-Droid. I don't mind however to include an APK here on github for future releases.

**Comment by IzzySoft** [comment]
> I don't mind however to include an APK here on github for future releases.

That would be a start, thanks @Moustachauve! Can you please leave a note here when that's ready (maybe reopen this issue and just close it when the APK is there, so the closure would send the notice)?

> I don't plan on publishing my app to F-Droid.

Would you be opposed to having it there if someone else took care for inclusion?

**Comment by Moustachauve** [comment]
I don't mind having my app on F-droid if someone want to take care of it

**Comment by eisengrau** [comment]
Please! Couching for the A PK and the F-Droid release!

**Comment by Moustachauve** [comment]
The APK for the latest release has been added to the release page https://github.com/Moustachauve/WLED-Native-Android/releases

**Comment by IzzySoft** [comment]
Thanks @Moustachauve! I just pulled it and ran it through my library scanner (which btw is also used by F-Droid), which then complained about this:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

5 offenders.
```

So it would not be eligible for F-Droid inclusion – and even for my repo I've got to think. Would it be possible to have a "foss build flavor" coming without those non-free components? Taking expected questions ahead:

* for alternative analytics (which should then be opt-in), you can find [some alternatives listed here](https://gitlab.com/-/snippets/1896503#acceptable-analytics). I guess the other 4 "offenders" have been dragged in my Crashlytics, but…
* should Firebase be needed by your app itself (why?), you could probably replace that by [appwrite](https://github.com/appwrite/appwrite) or [Supabase](https://supabase.com/)
* if that gets us rid of all 5 above, there'd be no need of a separate build flavor if it's fine for you, and we could even try to bring it to F-Droid.org itself. I could consider accepting it into my repo if at least Crashlytics would be gone (but ideally also the other things "reaching out to Google"; with those proprietary things you never know what else they do and don't tell you).

**Comment by Moustachauve** [comment]
@IzzySoft I just released a new version of the APK labelled "FOSS" that has all the analytic software stripped out (I believe). 

Just a note that even on the official APK not labelled FOSS, the analytic is 100% opt-in and is disabled by default. Now there is also a version where that code is not even included. The source code for that version can be found in the "foss" branch of this github project: https://github.com/Moustachauve/WLED-Native-Android/tree/foss

Let me know if there is anything more that would be required. I will try to update that branch and include an APK of that version for every future updates here.

**Comment by IzzySoft** [comment]
Thanks @Moustachauve! And just to point out: it's not that I'd not trust **you** – I just don't trust proprietary code, especially from a company known to be quite invasive to our privacy. So your help is much appreciated :star_struck: 

> I just released a new version of the APK labelled "FOSS" that has all the analytic software stripped out (I believe).

I can confirm that: my scanner didn't report any "offending libs" on the `*FOSS.apk`! So I've just added it to my repo, where it [should show up](https://apt.izzysoft.de/fdroid/index/apk/ca.cgagnier.wlednativeandroid) with the next sync around 6 pm UTC. Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) e.g. from your Readme if you like – there's one that would match the existing PlayStore badge well :smiley:

From what I can see (I didn't yet check the source tree for JARs/AARs etc), this branch should be fine for F-Droid.org even (just as F-Droid builds from tags, they'd then with each release need a tag which points into that branch – unless you make it a build flavor instead; for my repo it's fine as it is but you might consider bringing tag name and `versionName` in sync: it's a little confusing that v2.2.4 holds version 2.2.5 :wink:)

**Comment by natrius** [comment]
Interestingly enough, the app does not show up on f-droid anymore at all it seems.

**Comment by IzzySoft** [comment]
> Interestingly enough, the app does not show up on f-droid anymore at all it seems.

Was it ever listed at F-Droid.org? I doubt it (and I cannot find a corresponding `*.yml` there in the metadata directory). As pointed out above, the app is in [my repo](https://apt.izzysoft.de/fdroid) – which you'd first need to add/enable with your [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181).

**Comment by kudlav** [comment]
Hi, it's available in IzzyOnDroid F-Droid Repository. You can enable this
repository if you wan to use it. This repo uses apk files published on
GitHub release pages.

https://apt.izzysoft.de/fdroid/index/apk/ca.cgagnier.wlednativeandroid

**Comment by natrius** [comment]
Oooooh, the last f-droid update seems to have deleted my added repositories. That explains a lot. I was like "i have added your repository for a long time whut?" My fault :p

**Comment by IzzySoft** [comment]
> Oooooh, the last f-droid update seems to have deleted my added repositories.

Probably not the last but a previous one: yes, repository handling got a complete overhaul, and there was an alpha (as far as I remember) that had this bug. Solved meanwhile – as luckily is your issue now. Enjoy!

**Comment by IzzySoft** [comment]
> I just released a new version of the APK labelled "FOSS" that has all the analytic software stripped out (I believe).

While I can confirm that, looking at [the `build.gradle`](https://github.com/Moustachauve/WLED-Native-Android/blob/main/app/build.gradle#L113) it seems that if I built the app from source, Firebase would be back in. There's no build flavor to exclude that:

```gradle
    implementation platform('com.google.firebase:firebase-bom:32.7.2')
    implementation 'com.google.firebase:firebase-crashlytics-ktx:18.6.2'
    implementation 'com.google.firebase:firebase-perf-ktx:20.5.2'
```

It says `implementation` – so it would be applied always. And your next release would probably have it back in unless you offer another manually built APK. May I suggest establishing [build flavors](https://developer.android.com/build/build-variants) – e.g. `foss` and `google`, then making those `googleImplementation`, @Moustachauve?

**Comment by Moustachauve** [comment]
@IzzySoft I think that the main branch as of now can be considered free of proprietary code and would be compatible directly for F-droid.

**Comment by IzzySoft** [comment]
@Moustachauve I've sent the latest APK through our scanners, and it seems I can confirm: they no longer list any (known) proprietary dependency, congrats! The only things coming up with them are:

```
Dangerous flags:
----------------
* usesCleartextTraffic

SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

`usesCleartextTraffic`: I guess those WLED devices are inside the local network and have no certificate, so communication with them happens via plain `http` – but otherwise there's no unencrypted traffic?

As for `DEPENDENCY_INFO_BLOCK`, that can easily be avoided with a small addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

As there no longer is a `*FOSS*.apk` at your releases (no longer needed, as you already explained), I'll now adjust the YAML metadata of the app here so the other APK will be fetched. Once you've confirmed my guess on `usesCleartextTraffic` I'll add that to the app's "green list" – and with the next release, hopefully the `DEPENDENCY_INFO_BLOCK` is gone as well, so all should be excellent :smiley:

Next thing, I've just checked whether your app is reproducible (see: [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)) – and congrats, it is :partying_face: So v5.0.0 will show up with the next sync (around 7 pm UTC) having its green shield up, wonderful :smiley:

So the last thing remaining would be Fastlane metadata, enabling you to maintain how your app is presented (app description, graphics). I could send you a "starter package" with what is set up here at IzzyOnDroid currently, via PR, and you then are welcome to use the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for guidance with adjusting it to your desire. What do you say?
